### PR TITLE
Adding jenkins checks.

### PR DESCRIPTION
**Pull request by kwoodson**

### CODE REVIEW

**Comment by kwoodson** [comment]
ok to test

**Comment by kwoodson** [comment]
ok to test

**Comment by kwoodson** [comment]
ok to test

**Comment by kwoodson** [comment]
ok to test

**Comment by kwoodson** [comment]
ok to test

**Comment by kwoodson** [comment]
ok to test

**Comment by kwoodson** [comment]
ok to test

**Comment by twiest** [comment]
This is amazing work! :)     :+1:

**Pull request merged**
